# Generated by Django 5.0.4 on 2024-05-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('model',)},
        ),
    ]
